Fix pybind11 init template errors
With newer compiler toolchains, the following error message is triggered
during the build: "aer_circuit_binding.hpp:69:28: error: ambiguous
template instantiation" for `aer_uint` and similar methods. The issue
has to do with the lambda function used in the constructor becoming
ambiguous to the compiler. All of the lambdas simply forward the call to
public constructors and pybind11 supports binding to the constructors
directly, so that change is made here.